# Generated by Django 4.2.11 on 2024-03-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
