# Generated by Django 4.2.11 on 2024-06-11 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('item_store', '0006_alter_order_order_number_alter_review_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='basket',
            unique_together={('customer', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('order_number', 'product')},
        ),
    ]
