# Generated by Django 4.2.13 on 2024-06-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_store', '0008_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordernumber',
            name='status',
        ),
    ]
