# Generated by Django 5.1.2 on 2024-10-24 20:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_store', '0009_remove_ordernumber_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_basket_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='ordernumber',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
    ]
