# Generated by Django 5.1.2 on 2024-10-24 21:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_store', '0010_customer_total_basket_cost_ordernumber_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='total_basket_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=30),
        ),
        migrations.AlterField(
            model_name='ordernumber',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=30),
        ),
    ]
